version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/pg-data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      # - POSTGRES_DB=UnicornApi
   